import os
from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.environ["DATABASE_URL"]
ACCESS_TOKEN_SECRET = os.environ["ACCESS_TOKEN_SECRET"]
REFRESH_TOKEN_SECRET = os.environ["REFRESH_TOKEN_SECRET"]
COOKIE_SECURE = os.getenv("COOKIE_SECURE", "false").lower() == "true"
ACCESS_TOKEN_SECONDS = int(os.getenv("ACCESS_TOKEN_SECONDS", 900))
REFRESH_TOKEN_SECONDS = int(os.getenv("REFRESH_TOKEN_SECONDS", 604800))
SECRET_KEY = os.getenv("SECRET_KEY", ACCESS_TOKEN_SECRET)
JWT_ALGORITHM = os.getenv("JWT_ALGORITHM", "HS256")


class Settings:
    DATABASE_URL = DATABASE_URL
    ACCESS_TOKEN_SECRET = ACCESS_TOKEN_SECRET
    REFRESH_TOKEN_SECRET = REFRESH_TOKEN_SECRET
    COOKIE_SECURE = COOKIE_SECURE
    ACCESS_TOKEN_SECONDS = ACCESS_TOKEN_SECONDS
    REFRESH_TOKEN_SECONDS = REFRESH_TOKEN_SECONDS
    SECRET_KEY = SECRET_KEY
    JWT_ALGORITHM = JWT_ALGORITHM


settings = Settings()